task-120/add mobile version
Ilovemyteam/About-my-Team pull request #12
Opened 2024-02-27 20:41 UTC by OlenaPosternak

2024-02-27 23:08 UTC, NataPas2021 approved these changes

2024-02-28 03:08 UTC, Mazayw requested changes

2024-02-28 03:08 UTC, Mazayw commented on src/components/services/Title.tsx
Компонент семантично не коректний h2>div>span
Чи варто розділяти рядки таким чином? Як це буде виглядати в інших перекладах та інших розмірах?

2024-02-28 07:47 UTC, OlenaPosternak commented on src/components/services/ShowMoreButton.tsx
> +    isSwownMore,
ооо, дякую) виправила

2024-02-28 09:05 UTC, OlenaPosternak commented on src/components/services/ServicesTable.tsx
Винесла в коремий компонент список, мепнула.

2024-02-28 09:18 UTC, OlgaMykhailova commented on src/app/[locale]/layout.tsx
пропоную імпорт стилів поставити в кінець всіх імпортів

2024-02-28 09:29 UTC, OlenaPosternak commented on src/app/[locale]/layout.tsx
done)

2024-02-28 12:15 UTC, OlgaMykhailova approved these changes

2024-02-28 14:07 UTC, merged