adding section Our Team
Ilovemyteam/About-my-Team pull request #13
Opened 2024-02-27 22:57 UTC by NataPas2021

adding translation(uk);
adding main Component SectionOurTeam and components in it: Title, CategoriesList, TeamsList, ItemList

2024-02-28 03:16 UTC, Mazayw approved these changes

2024-02-28 05:47 UTC, OlenaPosternak requested changes

2024-02-28 05:47 UTC, OlenaPosternak commented on src/app/[locale]/page.tsx
> +        <main className="">
Оля перенесла хедер в layout. Не треба відміняти ці зміни

2024-02-28 05:47 UTC, OlenaPosternak commented on src/components/sectionOurTeam/ListItem.tsx
> +            <p className="text-base">{children}</p>
Нам потрібен цей закоментований код ?

2024-02-28 05:47 UTC, OlenaPosternak commented on src/components/sectionOurTeam/Title.tsx
> +            <div className="flex">
У нас є спільний компонент Title Wrapper з відступами для секцій. Використай його, будь ласка .

2024-02-28 06:38 UTC, OlgaMykhailova commented on src/components/sectionOurTeam/SectionOurTeam.tsx
зроби, будь ласка, назву секції ourTeamSection, щоб це було в одному стилі з уже існуючими

2024-02-28 08:08 UTC, NataPas2021 commented on src/components/sectionOurTeam/ListItem.tsx
> +            <p className="text-base">{children}</p>
я над кодом своєї секції ще працюю. тому закоментоване я залишаю для себе - якщо я це роблю, значить в мене є на те причини)

2024-02-28 08:13 UTC, NataPas2021 commented on src/app/[locale]/page.tsx
> +        <main className="">
в нас був конфлікт, який я вирішувала. мабуть, що випадково шось видалила

2024-02-28 08:30 UTC, NataPas2021 commented on src/components/sectionOurTeam/SectionOurTeam.tsx
ok)

2024-02-28 10:11 UTC, NataPas2021 reviewed
пофіксила

2024-02-28 10:15 UTC, OlenaPosternak requested changes

2024-02-28 10:15 UTC, OlenaPosternak commented on src/components/sectionOurTeam/Title.tsx
> +            <div className="flex">
Стягни будь ласка зміни та онови. Дякую

2024-02-28 10:22 UTC, NataPas2021 reviewed
added title wrapper

2024-02-28 12:02 UTC, OlgaMykhailova commented
мені здається після назв Учасники та Команди в тебе неправильні відступи вниз. Також самі категорії та назви проєктів повинні бути іншим шрифтом

![image](https://github.com/Ilovemyteam/About-my-Team/assets/100313107/c8fd3181-eef0-4e64-8790-e234a6277d74)

![image](https://github.com/Ilovemyteam/About-my-Team/assets/100313107/6ba592d7-0f24-4744-8f52-4503ede79f23)

2024-02-28 12:06 UTC, OlenaPosternak requested changes

2024-02-28 12:06 UTC, OlenaPosternak commented on src/components/sectionOurTeam/ListItem.tsx
> +            <p className="text-base">{children}</p>
Тоді тут або має бути аргументований коментар чому ти лишаєш цей код, або прибрати.  Закоментований код це недуже ок.

2024-02-28 13:45 UTC, OlgaMykhailova requested changes

2024-02-28 19:18 UTC, OlgaMykhailova approved these changes

2024-02-28 21:25 UTC, NataPas2021 reviewed
resolved conflicts

2024-02-28 21:27 UTC, NataPas2021 reviewed
done

2024-02-29 09:19 UTC, OlenaPosternak approved these changes

2024-02-29 09:19 UTC, merged