Multilingualism
Ilovemyteam/About-my-Team pull request #3
Opened 2024-02-19 16:11 UTC by OlgaMykhailova

Додала налаштування для мультимовності. Три словники - український, англійський та польський. Можна перевірити зміну мови в адресному рядку - додати uk, en, pl. На домашній сторінці буде змінюватися текст в одному рядку, додала для тесту. Налаштувала метаданні для відображення в залежності від мови. В словнику тестові дані, потім тексти треба буде змінити.

2024-02-20 00:02 UTC, Mazayw requested changes

2024-02-20 00:02 UTC, Mazayw commented on .eslintrc.json
> +        "@typescript-eslint/no-explicit-any": "off"
Потрібно змінити на:
"@typescript-eslint/no-explicit-any": "error"

2024-02-20 13:14 UTC, OlgaMykhailova commented on .eslintrc.json
> +        "@typescript-eslint/no-explicit-any": "off"
у нас в документації next-intl вказаний тип any

![image](https://github.com/Ilovemyteam/About-my-Team/assets/100313107/b8ee99f8-6480-4ff4-95f7-15129f3b9a45)

https://next-intl-docs.vercel.app/docs/getting-started/app-router

2024-02-20 13:16 UTC, OlgaMykhailova commented on messages/en.json
> +        "description": "Створюємо миттєвість у цифровому світі: ефектні лендінги та сайти під ключ"
виправила

2024-02-22 13:35 UTC, Mazayw commented on src/i18n.ts
> +    if (!locales.includes(locale as string)) notFound();
Думаю, тут краще описати тип через Type Annotation (описати тип у 7 рядку, без вткористання "as")

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions

"It's generally recommended to use type assertions with caution and only when you have a good reason to believe that the type you're asserting is indeed the correct type at runtime. In most cases, using type annotations and letting TypeScript infer types is a more robust approach for catching type-related errors during compilation."

2024-02-22 15:34 UTC, OlenaPosternak approved these changes

2024-02-23 03:38 UTC, Mazayw approved these changes

2024-02-23 03:39 UTC, merged