Added library Playwright for testing on 3 different browser engines
Ilovemyteam/About-my-Team pull request #8
Opened 2024-02-25 19:33 UTC by IraMira333

<img width="1728" alt="Знімок екрана 2024-02-23 о 23 03 39" src="https://github.com/Ilovemyteam/About-my-Team/assets/119503034/e626d6a4-7647-47b3-bffe-93f1439fe01b">
<img width="1728" alt="Знімок екрана 2024-02-23 о 23 04 16" src="https://github.com/Ilovemyteam/About-my-Team/assets/119503034/631cf02c-26d1-42f1-9fa7-3ff924eb8cf1">
<img width="1728" alt="Знімок екрана 2024-02-23 о 23 04 53" src="https://github.com/Ilovemyteam/About-my-Team/assets/119503034/f640956d-fb57-4683-a9e9-faf1a84b7bb5">

2024-02-27 12:02 UTC, NataPas2021 approved these changes

2024-02-28 02:31 UTC, Mazayw requested changes

2024-02-28 02:31 UTC, Mazayw commented on .env
Цей файл повинен бути в ігнорі

2024-02-28 02:31 UTC, Mazayw commented on .github/workflows/playwright.yml
Думаю, варто було б вказати версію NodeJs
Розглянь можливість використання кешу https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

2024-02-28 02:31 UTC, Mazayw commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Що буде, якщо не буде доступу до змінної NEXT_PUBLIC_PLAYWRIGHT?

2024-02-28 02:31 UTC, Mazayw commented on playwright.config.ts
> +    retries: process.env.CI ? 2 : 0,
Що це за цифри 2 і 0 -додай коментар, або зроби змінні, які б описали ці значення

2024-02-28 02:31 UTC, Mazayw commented on tests/homePage.spec.ts
> +test("test", async ({ page }) => {
Краще писати більш детальний та змістовний опис тесту.

2024-02-28 02:31 UTC, Mazayw commented on tests/homePage.spec.ts
> +    ).toBeVisible();
Як це можна записати для легшого читання коду:
const testJestHeading = await page.getByRole("heading", { name: "TEST JEST" });
await expect(testJestHeading).toBeVisible();

2024-02-28 02:31 UTC, Mazayw commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
А якщо використати window.location замість прописування змінної вручну?

2024-02-28 06:17 UTC, IraMira333 commented on tests/homePage.spec.ts
> +test("test", async ({ page }) => {
Це пише сам генератор тестів і це типу заглушка, якщо буде реальна сторінка, будуть більш детальні описи.

2024-02-28 06:19 UTC, IraMira333 commented on tests/homePage.spec.ts
> +    ).toBeVisible();
Це також пише сам генератор тестів. Як на мене, читається легко, якщо декілька разів поюзати, звикаєш)) 
І це також тест-заглушка, в реальному, звісно і змінні можна краще назвати.

2024-02-28 06:21 UTC, IraMira333 commented on .github/workflows/playwright.yml
with:
                  node-version: 18
Вказана

2024-02-28 06:27 UTC, IraMira333 commented on playwright.config.ts
> +    retries: process.env.CI ? 2 : 0,
Це вказує, що якщо тести виконуються в середовищі CI, то їм дозволяється робити 2 спроби перезапуску у разі невдачі (retries), а якщо тести виконуються локально, то не робити жодних спроб перезапуску (retries: 0).

2024-02-28 06:38 UTC, IraMira333 commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
якщо не буде доступу до змінної NEXT_PUBLIC_PLAYWRIGHT, отримаємо undefined як значення url. Це не добре, можна організувати перевірку, але доступ до перемінної має бути.

Використання window.location у браузерному середовищі не вирішить проблему, пов'язану з відсутністю NEXT_PUBLIC_PLAYWRIGHT в середовищі виконання.

Оскільки NEXT_PUBLIC_PLAYWRIGHT  у нас — це змінна середовища, вона повинна бути доступною у нашому серверному середовищі виконання (де ми запускаємо сервер). window.location працює в браузерному JavaScript і не надає доступ до змінних середовища на сервері.

Варіантів немає, ця перемінна має бути доступною.

2024-02-28 06:38 UTC, IraMira333 commented on .env
Не зрозуміла. 

NEXT_PUBLIC_PLAYWRIGHT='http://localhost:3000'

2024-02-28 13:20 UTC, Mazayw commented on .env
https://salferrarello.com/add-env-to-gitignore/

2024-02-28 13:22 UTC, Mazayw commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Думаю, тут потрібно додати дефолтне значення, якщо не вдасться прочитати змінну

2024-02-28 13:23 UTC, Mazayw commented on playwright.config.ts
> +    retries: process.env.CI ? 2 : 0,
https://en.wikipedia.org/wiki/Magic_number_(programming)

2024-02-28 13:51 UTC, IraMira333 commented on .env
ААААА так, додала в gitignore.

2024-02-28 13:53 UTC, IraMira333 commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Згідно документаціі не додають, а якщо додавати, то який URL? 

Як на мене, те що в .env то найнадійніше і точно прочитається.

2024-02-28 13:56 UTC, IraMira333 commented on playwright.config.ts
> +    retries: process.env.CI ? 2 : 0,
Не дуже зрозуміла що з цієї статті маю винести)
Ці цифри йдуть з документаціі і слово retries - спроби, наче пояснює що мається не увазі.
Можу додати коментар, не хочеться вводити додаткові змінні.
На якій мові внести коментар?

2024-02-28 13:57 UTC, IraMira333 commented on playwright.config.ts
> +    retries: process.env.CI ? 2 : 0,
Напишу на англ)

2024-02-28 14:43 UTC, IraMira333 commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Я б поки що залишила так, якщо будуть питання, повернемось до цього.

2024-02-28 23:22 UTC, Mazayw commented on .env
Ще видали з останнього коміту 
git rm

2024-02-28 23:32 UTC, Mazayw commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Ок
А що буде, якщо забути вказати NEXT_PUBLIC_PLAYWRIGHT?

2024-02-29 09:27 UTC, IraMira333 commented on .env
Не зрозуміла що саме видалити і звідки

2024-02-29 09:32 UTC, IraMira333 commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
Скаже що не може звязатись із сервером. Видасть помилку: Error: page.goto: Protocol error (Page.navigate): Invalid url: "/"
Але якщо вказати потрібний URL в самому тесті, то байдуже чи є NEXT_PUBLIC_PLAYWRIGHT:
test("test", async ({ page }) => {
    await page.goto("http://localhost:3000");

2024-02-29 10:18 UTC, IraMira333 commented on playwright.config.ts
> +        baseURL: process.env.NEXT_PUBLIC_PLAYWRIGHT,
І це ж тільки тест, він ніяк не впливає на сайт. Якщо він не знайде шлях, то не дозволить мерджити ПР і все.

2024-02-29 14:57 UTC, merged